// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using System.Numerics;
using VM2.Model;

namespace VM2.AccesoDatos
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext()
        {
        }

        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Placas> Placas { get; set; }
        public virtual DbSet<TipoPersonas> TipoPersonas { get; set; }
        public virtual DbSet<TipoVehiculos> TipoVehiculos { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Vehiculos> Vehiculos { get; set; }


    }

}

